module.exports = {
  someSidebar: {
    '索引': ['index', 'index2'],
    '技术实现': ['technology/im/index', 'default'],
    '开发环境': ['dev/index'],
    '学习资源': ['learnResources/README'],
    '应用程序': ['applications/index'],
    'API': ['api/index'],
    'WebFramework': ['WebFramework/index'],
    'Linux': ['Linux/index'],
    '系统设计': ['SystemDesign/index'],
    '数据存储': ['dataStorage/NumberSystems', 'dataStorage/Representation', 'dataStorage/StoringTextInBinary'],
    '数据操控': ['dataOperation/CircuitsAndLogic/README', 'dataOperation/cpu/README', 'dataOperation/io/README', 'dataOperation/memory/README'],
    '操作系统': ['default'],
    '计算机网络': ['Network/index'],
    '算法与数据结构': ['default'],
    '程序设计语言': ['Deno/index'],
    '软件工程': ['default'],
    '数据抽象': ['default'],
    '数据库': ['database/theory'],
    '计算机图形学': ['default'],
    '人工智能': ['default'],
    '计算理论': ['default'],
    'OpenGL': ['openGL/BufferObject/QQuickFrameBufferObject'],
    '附录': ['default'],
  },
};
